/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLySanPham;

import Main.HomeFrame;
import java.awt.Color;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import utils.DiaNhac;
import utils.DiaPhim;
import utils.Sach;

/**
 *
 * @author h
 */
public class NhapHang extends javax.swing.JPanel {

    private int ma_mh;
    /**
     * Creates new form NhapHang
     */
    public NhapHang() {
        initComponents();
        
        setMaMatHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNhapHang = new javax.swing.JLabel();
        PanelInfoNhapHang = new javax.swing.JPanel();
        lbMaMh = new javax.swing.JLabel();
        lbTenMatHangNhapHang = new javax.swing.JLabel();
        lbLoaiMatHangNhapHang = new javax.swing.JLabel();
        lbSoLuongNhapHang = new javax.swing.JLabel();
        lbGiaMuaNhapHang = new javax.swing.JLabel();
        lbGiaBanNhapHang = new javax.swing.JLabel();
        txtfMaMHNhapHang = new javax.swing.JTextField();
        txtfTenMatHangNhapHang = new javax.swing.JTextField();
        txtfSoLuongNhapHang = new javax.swing.JTextField();
        txtfGiaMuaNhapHang = new javax.swing.JTextField();
        txtfGiaBanNhapHang = new javax.swing.JTextField();
        comBLoaiMHNhapHang = new javax.swing.JComboBox<>();
        PanelReferenceNhapHang = new javax.swing.JPanel();
        lbRef1NhapHang = new javax.swing.JLabel();
        lbRef2NhapHang = new javax.swing.JLabel();
        lbRef3NhapHang = new javax.swing.JLabel();
        txtfRef1NhapHang = new javax.swing.JTextField();
        txtfRef2NhapHang = new javax.swing.JTextField();
        txtfRef3NhapHang = new javax.swing.JTextField();
        lbTheLoaiNhapHang = new javax.swing.JLabel();
        txtfTheLoaiNhapHang = new javax.swing.JTextField();
        btXoaNhapHang = new javax.swing.JButton();
        btLuuNhapHang = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        lbNhapHang.setText("Nhập hàng");

        lbMaMh.setText("Mã Mặt Hàng");

        lbTenMatHangNhapHang.setText("Tên Mặt Hàng");

        lbLoaiMatHangNhapHang.setText("Loại Mặt Hàng");

        lbSoLuongNhapHang.setText("Số Lượng");

        lbGiaMuaNhapHang.setText("Giá Mua");

        lbGiaBanNhapHang.setText("Giá Bán");

        txtfMaMHNhapHang.setEditable(false);

        txtfTenMatHangNhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfTenMatHangNhapHangFocusGained(evt);
            }
        });

        txtfSoLuongNhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfSoLuongNhapHangFocusGained(evt);
            }
        });

        txtfGiaMuaNhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfGiaMuaNhapHangFocusGained(evt);
            }
        });

        txtfGiaBanNhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfGiaBanNhapHangFocusGained(evt);
            }
        });

        comBLoaiMHNhapHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đĩa Nhạc", "Đĩa Phim", "Các Loại Sách" }));
        comBLoaiMHNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBLoaiMHNhapHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInfoNhapHangLayout = new javax.swing.GroupLayout(PanelInfoNhapHang);
        PanelInfoNhapHang.setLayout(PanelInfoNhapHangLayout);
        PanelInfoNhapHangLayout.setHorizontalGroup(
            PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaMh)
                    .addComponent(lbTenMatHangNhapHang)
                    .addComponent(lbLoaiMatHangNhapHang)
                    .addComponent(lbSoLuongNhapHang)
                    .addComponent(lbGiaMuaNhapHang)
                    .addComponent(lbGiaBanNhapHang))
                .addGap(120, 120, 120)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtfMaMHNhapHang)
                        .addComponent(txtfTenMatHangNhapHang)
                        .addComponent(txtfSoLuongNhapHang)
                        .addComponent(txtfGiaMuaNhapHang)
                        .addComponent(txtfGiaBanNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addComponent(comBLoaiMHNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PanelInfoNhapHangLayout.setVerticalGroup(
            PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoNhapHangLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaMh)
                    .addComponent(txtfMaMHNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenMatHangNhapHang)
                    .addComponent(txtfTenMatHangNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoaiMatHangNhapHang)
                    .addComponent(comBLoaiMHNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuongNhapHang)
                    .addComponent(txtfSoLuongNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaMuaNhapHang)
                    .addComponent(txtfGiaMuaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PanelInfoNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaBanNhapHang)
                    .addComponent(txtfGiaBanNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbRef1NhapHang.setText("Nhạc sĩ");

        lbRef2NhapHang.setText("Ca sĩ");

        lbRef3NhapHang.setText("Albumn");

        txtfRef1NhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfRef1NhapHangFocusGained(evt);
            }
        });

        txtfRef2NhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfRef2NhapHangFocusGained(evt);
            }
        });

        txtfRef3NhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfRef3NhapHangFocusGained(evt);
            }
        });

        lbTheLoaiNhapHang.setText("Thể Loại");

        txtfTheLoaiNhapHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfTheLoaiNhapHangFocusGained(evt);
            }
        });

        javax.swing.GroupLayout PanelReferenceNhapHangLayout = new javax.swing.GroupLayout(PanelReferenceNhapHang);
        PanelReferenceNhapHang.setLayout(PanelReferenceNhapHangLayout);
        PanelReferenceNhapHangLayout.setHorizontalGroup(
            PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReferenceNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRef1NhapHang)
                    .addComponent(lbRef2NhapHang)
                    .addComponent(lbRef3NhapHang)
                    .addComponent(lbTheLoaiNhapHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfRef1NhapHang)
                    .addComponent(txtfRef2NhapHang)
                    .addComponent(txtfRef3NhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtfTheLoaiNhapHang))
                .addContainerGap())
        );
        PanelReferenceNhapHangLayout.setVerticalGroup(
            PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReferenceNhapHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef1NhapHang)
                    .addComponent(txtfRef1NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef2NhapHang)
                    .addComponent(txtfRef2NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRef3NhapHang)
                    .addComponent(txtfRef3NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(PanelReferenceNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTheLoaiNhapHang)
                    .addComponent(txtfTheLoaiNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        btXoaNhapHang.setText("Xóa");
        btXoaNhapHang.setPreferredSize(new java.awt.Dimension(85, 23));
        btXoaNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaNhapHangActionPerformed(evt);
            }
        });

        btLuuNhapHang.setText("Lưu");
        btLuuNhapHang.setPreferredSize(new java.awt.Dimension(85, 23));
        btLuuNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuNhapHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNhapHang)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInfoNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelReferenceNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(btXoaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btLuuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNhapHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelReferenceNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelInfoNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXoaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLuuNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comBLoaiMHNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBLoaiMHNhapHangActionPerformed
        // TODO add your handling code here:
        String mes = (String) comBLoaiMHNhapHang.getSelectedItem();
        switch(mes){
            case "Đĩa Nhạc":
                lbRef1NhapHang.setText("Nhạc sĩ");
                lbRef2NhapHang.setText("Ca sĩ");
                lbRef3NhapHang.setText("Albumn");
                break;
            case "Đĩa Phim":
                lbRef1NhapHang.setText("Đạo diễn");
                lbRef2NhapHang.setText("Diễn viên");
                lbRef3NhapHang.setText("Chất lượng");
                break;
            default:
                lbRef1NhapHang.setText("Tác giả");
                lbRef2NhapHang.setText("NXB");
                lbRef3NhapHang.setText("Ngôn ngữ");
                break;
        }
    }//GEN-LAST:event_comBLoaiMHNhapHangActionPerformed

    private void btXoaNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaNhapHangActionPerformed
        // TODO add your handling code here:
        txtfTenMatHangNhapHang.setText("");
        comBLoaiMHNhapHang.setSelectedIndex(0);
        txtfSoLuongNhapHang.setText("");
        txtfGiaMuaNhapHang.setText("");
        txtfGiaBanNhapHang.setText("");
        
        txtfRef1NhapHang.setText("");
        txtfRef2NhapHang.setText("");
        txtfRef3NhapHang.setText("");
        txtfTheLoaiNhapHang.setText("");
    }//GEN-LAST:event_btXoaNhapHangActionPerformed

    private void btLuuNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuNhapHangActionPerformed
        // TODO add your handling code here:
        try{
            String maMH = txtfMaMHNhapHang.getText().toString();
            String ten = txtfTenMatHangNhapHang.getText().toString();
            String loaiSP = comBLoaiMHNhapHang.getSelectedItem().toString();
            int soLuong = Integer.parseInt(txtfSoLuongNhapHang.getText().toString());
            int giaMua = Integer.parseInt(txtfGiaMuaNhapHang.getText().toString());
            int giaBan = Integer.parseInt(txtfGiaBanNhapHang.getText().toString());
            
            String ref1 = txtfRef1NhapHang.getText().toString();
            String ref2 = txtfRef2NhapHang.getText().toString();
            String ref3 = txtfRef3NhapHang.getText().toString();
            String theLoai = txtfTheLoaiNhapHang.getText().toString();
            if(isAvailable(ten,soLuong,giaMua,giaBan)){
                switch(loaiSP){
                    case "Đĩa Nhạc":
                        DiaNhac diaNhacMoi = new DiaNhac(ten,loaiSP,ref1,ref2,ref3,theLoai,soLuong,giaMua,giaBan);
                        HomeFrame.cuaHang.getListDiaNhac().add(diaNhacMoi);
                        HomeFrame.cuaHang.nhapKhoHang("Đĩa Nhạc");
                        break;
                    case "Đĩa Phim":
                        DiaPhim diaPhimMoi = new DiaPhim(ten,loaiSP,ref1,ref2,ref3,theLoai,soLuong,giaMua,giaBan);
                        HomeFrame.cuaHang.getListDiaPhim().add(diaPhimMoi);
                        HomeFrame.cuaHang.nhapKhoHang("Đĩa Phim");
                        break;
                    default:
                        Sach sachMoi = new Sach(ten,loaiSP,ref1,ref2,ref3,theLoai,soLuong,giaMua,giaBan);
                        HomeFrame.cuaHang.getListSach().add(sachMoi);
                        HomeFrame.cuaHang.nhapKhoHang("Các Loại Sách");
                        break;
                }
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                setMaMatHang();
                
            }
        }catch (Exception e){
            try{
                int soLuong = Integer.parseInt(txtfSoLuongNhapHang.getText().toString());
            }catch (NumberFormatException e1){
                notifyError(txtfSoLuongNhapHang,"Số lượng phải là số tự nhiên");
            }
            
            
            try{
                int giaMua = Integer.parseInt(txtfGiaMuaNhapHang.getText().toString());
            }catch (NumberFormatException e1){
                notifyError(txtfGiaMuaNhapHang,"Giá mua phải là số tự nhiên");
            }
            
            try{
                int giaBan = Integer.parseInt(txtfGiaBanNhapHang.getText().toString());
            }catch (NumberFormatException e1){
                notifyError(txtfGiaBanNhapHang,"Giá mua phải là số tự nhiên");
            }
            
        }
    }//GEN-LAST:event_btLuuNhapHangActionPerformed

    private void txtfTenMatHangNhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTenMatHangNhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfTenMatHangNhapHangFocusGained

    private void txtfSoLuongNhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfSoLuongNhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfSoLuongNhapHangFocusGained

    private void txtfGiaMuaNhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfGiaMuaNhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfGiaMuaNhapHangFocusGained

    private void txtfGiaBanNhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfGiaBanNhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfGiaBanNhapHangFocusGained

    private void txtfRef1NhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfRef1NhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfRef1NhapHangFocusGained

    private void txtfRef2NhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfRef2NhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfRef2NhapHangFocusGained

    private void txtfRef3NhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfRef3NhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfRef3NhapHangFocusGained

    private void txtfTheLoaiNhapHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTheLoaiNhapHangFocusGained
        // TODO add your handling code here:
        handleWhenBeFocus((JTextField) evt.getComponent());
    }//GEN-LAST:event_txtfTheLoaiNhapHangFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfoNhapHang;
    private javax.swing.JPanel PanelReferenceNhapHang;
    private javax.swing.JButton btLuuNhapHang;
    private javax.swing.JButton btXoaNhapHang;
    private javax.swing.JComboBox<String> comBLoaiMHNhapHang;
    private javax.swing.JLabel lbGiaBanNhapHang;
    private javax.swing.JLabel lbGiaMuaNhapHang;
    private javax.swing.JLabel lbLoaiMatHangNhapHang;
    private javax.swing.JLabel lbMaMh;
    private javax.swing.JLabel lbNhapHang;
    private javax.swing.JLabel lbRef1NhapHang;
    private javax.swing.JLabel lbRef2NhapHang;
    private javax.swing.JLabel lbRef3NhapHang;
    private javax.swing.JLabel lbSoLuongNhapHang;
    private javax.swing.JLabel lbTenMatHangNhapHang;
    private javax.swing.JLabel lbTheLoaiNhapHang;
    private javax.swing.JTextField txtfGiaBanNhapHang;
    private javax.swing.JTextField txtfGiaMuaNhapHang;
    private javax.swing.JTextField txtfMaMHNhapHang;
    private javax.swing.JTextField txtfRef1NhapHang;
    private javax.swing.JTextField txtfRef2NhapHang;
    private javax.swing.JTextField txtfRef3NhapHang;
    private javax.swing.JTextField txtfSoLuongNhapHang;
    private javax.swing.JTextField txtfTenMatHangNhapHang;
    private javax.swing.JTextField txtfTheLoaiNhapHang;
    // End of variables declaration//GEN-END:variables

    private boolean isAvailable(String ten, int soLuong, int giaMua, int giaBan ) {
        boolean result = true;
        if(ten.equals("")){
            notifyError(txtfTenMatHangNhapHang);
            result = false;
        }
        if(soLuong == 0){
            notifyError(txtfSoLuongNhapHang);
            result = false;
        }
        if(soLuong < 0){
            notifyError(txtfSoLuongNhapHang,"Số lượng không thể âm!");
            result = false;
        }
        
        if(giaMua == 0){
            notifyError(txtfGiaMuaNhapHang);
            result = false;
        }
        if(giaMua < 0){
            notifyError(txtfGiaMuaNhapHang,"Giá mua không thể âm!");
            result = false;
        }
        
        if(giaBan == 0){
            notifyError(txtfGiaBanNhapHang);
            result = false;
        }
        if(giaBan < 0){
            notifyError(txtfGiaBanNhapHang,"Giá bán không thể âm!");
            result = false;
        }
        
        return result;
    }
    
    private void notifyError(javax.swing.JTextField smt) {
        smt.setText("Không được để trống");
        smt.setForeground(java.awt.Color.RED);
    }
    
    private void notifyError(javax.swing.JTextField smt,String error) {
        smt.setText(error);
        smt.setForeground(java.awt.Color.RED);
    }
    
    private void handleWhenBeFocus(javax.swing.JTextField smt){
        if(smt.getForeground() == Color.RED){
            smt.setText("");
            smt.setForeground(Color.black);
        }
    }

    private void setMaMatHang() {
        int slDiaNhac = HomeFrame.cuaHang.getListDiaNhac().size();
        int slDiaPhim = HomeFrame.cuaHang.getListDiaPhim().size();
        int slSach = HomeFrame.cuaHang.getListSach().size();
        ma_mh = slDiaNhac + slDiaPhim+slSach+1;
        txtfMaMHNhapHang.setText("SP"+ma_mh);
    }
    
    

}
